Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/local/lib/python3.10/dist-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Tokenisasi teks
berita_tokenized = sent_tokenize(berita_cleaned)
berita_tokenized
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mLookupError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-8-76cc7a9a83f8>[0m in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m [0;31m# Tokenisasi teks[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mberita_tokenized[0m [0;34m=[0m [0msent_tokenize[0m[0;34m([0m[0mberita_cleaned[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0mberita_tokenized[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/nltk/tokenize/__init__.py[0m in [0;36msent_tokenize[0;34m(text, language)[0m
[1;32m    104[0m     [0;34m:[0m[0mparam[0m [0mlanguage[0m[0;34m:[0m [0mthe[0m [0mmodel[0m [0mname[0m [0;32min[0m [0mthe[0m [0mPunkt[0m [0mcorpus[0m[0;34m[0m[0;34m[0m[0m
[1;32m    105[0m     """
[0;32m--> 106[0;31m     [0mtokenizer[0m [0;34m=[0m [0mload[0m[0;34m([0m[0;34mf"tokenizers/punkt/{language}.pickle"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    107[0m     [0;32mreturn[0m [0mtokenizer[0m[0;34m.[0m[0mtokenize[0m[0;34m([0m[0mtext[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    108[0m [0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/nltk/data.py[0m in [0;36mload[0;34m(resource_url, format, cache, verbose, logic_parser, fstruct_reader, encoding)[0m
[1;32m    748[0m [0;34m[0m[0m
[1;32m    749[0m     [0;31m# Load the resource.[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 750[0;31m     [0mopened_resource[0m [0;34m=[0m [0m_open[0m[0;34m([0m[0mresource_url[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    751[0m [0;34m[0m[0m
[1;32m    752[0m     [0;32mif[0m [0mformat[0m [0;34m==[0m [0;34m"raw"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/nltk/data.py[0m in [0;36m_open[0;34m(resource_url)[0m
[1;32m    874[0m [0;34m[0m[0m
[1;32m    875[0m     [0;32mif[0m [0mprotocol[0m [0;32mis[0m [0;32mNone[0m [0;32mor[0m [0mprotocol[0m[0;34m.[0m[0mlower[0m[0;34m([0m[0;34m)[0m [0;34m==[0m [0;34m"nltk"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 876[0;31m         [0;32mreturn[0m [0mfind[0m[0;34m([0m[0mpath_[0m[0;34m,[0m [0mpath[0m [0;34m+[0m [0;34m[[0m[0;34m""[0m[0;34m][0m[0;34m)[0m[0;34m.[0m[0mopen[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    877[0m     [0;32melif[0m [0mprotocol[0m[0;34m.[0m[0mlower[0m[0;34m([0m[0;34m)[0m [0;34m==[0m [0;34m"file"[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    878[0m         [0;31m# urllib might not use mode='rb', so handle this one ourselves:[0m[0;34m[0m[0;34m[0m[0m

[0;32m/usr/local/lib/python3.10/dist-packages/nltk/data.py[0m in [0;36mfind[0;34m(resource_name, paths)[0m
[1;32m    581[0m     [0msep[0m [0;34m=[0m [0;34m"*"[0m [0;34m*[0m [0;36m70[0m[0;34m[0m[0;34m[0m[0m
[1;32m    582[0m     [0mresource_not_found[0m [0;34m=[0m [0;34mf"\n{sep}\n{msg}\n{sep}\n"[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 583[0;31m     [0;32mraise[0m [0mLookupError[0m[0;34m([0m[0mresource_not_found[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    584[0m [0;34m[0m[0m
[1;32m    585[0m [0;34m[0m[0m

[0;31mLookupError[0m: 
**********************************************************************
  Resource [93mpunkt[0m not found.
  Please use the NLTK Downloader to obtain the resource:

  [31m>>> import nltk
  >>> nltk.download('punkt')
  [0m
  For more information see: https://www.nltk.org/data.html

  Attempted to load [93mtokenizers/punkt/PY3/english.pickle[0m

  Searched in:
    - '/root/nltk_data'
    - '/usr/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************


